[package]
name = "wca_comp_overview"
version = "0.1.0"
edition = "2021"

[dependencies]
maud = "0.26.0"
reqwest = { version = "0.12.2", features = ["blocking"] }
scraper = "0.19.0"
webbrowser = "0.8.13"
